name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_native_splash: ^2.3.6
  line_icons: ^2.0.3
  intl_phone_field: ^3.2.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  animated_bottom_navigation_bar: ^1.3.0
  auto_size_text: ^3.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/logo_light.png
   - assets/logo_dark.png
   - assets/lottie_files/
   - assets/flags/
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/font/Montserrat/static/Montserrat-Regular.ttf

flutter_native_splash:
  android: true
  ios: true

  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/logo_light.png
  image_dark: assets/logo_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/logo_light.png
    image_dark: assets/logo_dark.png
  fullscreen: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
